# coding: utf-8
# SPDX-License-Identifier: GPL-3.0-or-later
# 应用配置集中处；环境变量可覆盖打包/部署时的值。
# Central application configuration; environment variables may override build values.
"""应用运行时与构建配置。"""

from __future__ import annotations

import logging
import os


LOGGER = logging.getLogger(__name__)


def _env(name: str, default: str) -> str:
    value = os.getenv(name)
    return value if value else default


def _env_int(name: str, default: int, minimum: int, maximum: int) -> int:
    value = os.getenv(name)
    try:
        parsed = int(value) if value else default
    except ValueError:
        LOGGER.warning("环境变量 %s 不是有效整数，使用默认值", name)
        return default
    return max(minimum, min(parsed, maximum))


def _env_bool(name: str, default: bool) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    normalized = value.strip().casefold()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    LOGGER.warning("环境变量 %s 不是有效布尔值，使用默认值", name)
    return default


APP_TITLE = _env("MCNETEASE_APP_TITLE", "我的世界中国版打包工具")
SPLASH_SUBTITLE = _env("MCNETEASE_SPLASH_SUBTITLE", "正在加载，请稍候…")
APP_VERSION = _env("MCNETEASE_APP_VERSION", "v0.1.0.7")
UPDATE_REPO = _env("MCNETEASE_UPDATE_REPO", "aki-riko/MCNeteaseToolPE")
UPDATE_ASSET_KEYWORD = _env("MCNETEASE_UPDATE_ASSET_KEYWORD", "Setup")
PROJECT_HOMEPAGE = _env(
    "MCNETEASE_PROJECT_HOMEPAGE",
    f"https://github.com/{UPDATE_REPO}",
)
PRISMQML_HOMEPAGE = _env(
    "MCNETEASE_PRISMQML_HOMEPAGE",
    "https://github.com/aki-riko/PrismQML",
)
INSTALLER_SILENT_ARGS = _env(
    "MCNETEASE_INSTALLER_SILENT_ARGS",
    "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /CLOSEAPPLICATIONS /RESTARTAPPLICATIONS",
)
ZIP_COMPRESSION_LEVEL = _env_int("MCNETEASE_ZIP_COMPRESSION_LEVEL", 6, 0, 9)
AUDIT_MAX_FILE_NAME_CHARS = _env_int(
    "MCNETEASE_AUDIT_MAX_FILE_NAME_CHARS", 0, 0, 255
)
AUDIT_MAX_TEXTURE_DIMENSION = _env_int(
    "MCNETEASE_AUDIT_MAX_TEXTURE_DIMENSION", 0, 0, 32768
)
AUDIT_MAX_NETWORK_VERSION = _env_int(
    "MCNETEASE_AUDIT_MAX_NETWORK_VERSION", 0, 0, 2_147_483_647
)
MCP_PORT_MIN = 1024
MCP_PORT_MAX = 65535
MCP_HOST = _env("MCNETEASE_MCP_HOST", "127.0.0.1").strip()
MCP_PORT = _env_int("MCNETEASE_MCP_PORT", 8765, MCP_PORT_MIN, MCP_PORT_MAX)
MCP_PATH = _env("MCNETEASE_MCP_PATH", "/mcp").strip()
MCP_STOP_TIMEOUT_MS = _env_int("MCNETEASE_MCP_STOP_TIMEOUT_MS", 2000, 100, 10_000)
TRACY_HOST = _env("MCNETEASE_TRACY_HOST", "127.0.0.1").strip()
TRACY_PORT = _env_int("MCNETEASE_TRACY_PORT", 8086, 1, 65_535)
TRACY_CAPTURE_SECONDS = _env_int(
    "MCNETEASE_TRACY_CAPTURE_SECONDS", 10, 1, 60
)
TRACY_CAPTURE_COOLDOWN_MS = _env_int(
    "MCNETEASE_TRACY_CAPTURE_COOLDOWN_MS", 1000, 0, 10_000
)
TRACY_PROBE_INTERVAL_MS = _env_int(
    "MCNETEASE_TRACY_PROBE_INTERVAL_MS", 1500, 250, 10_000
)
PERFORMANCE_AUTO_STABILITY_MS = _env_int(
    "MCNETEASE_PERFORMANCE_AUTO_STABILITY_MS", 20_000, 0, 300_000
)
AIRPERF_RUNTIME_DIR = _env("MCNETEASE_AIRPERF_RUNTIME_DIR", "").strip()
AIRPERF_HOST = _env("MCNETEASE_AIRPERF_HOST", "127.0.0.1").strip()
AIRPERF_X64_PORT = _env_int("MCNETEASE_AIRPERF_X64_PORT", 10064, 1, 65_535)
AIRPERF_X86_PORT = _env_int("MCNETEASE_AIRPERF_X86_PORT", 10032, 1, 65_535)
AIRPERF_RPC_TIMEOUT_MS = _env_int(
    "MCNETEASE_AIRPERF_RPC_TIMEOUT_MS", 10_000, 1000, 30_000
)
AIRPERF_START_TIMEOUT_MS = _env_int(
    "MCNETEASE_AIRPERF_START_TIMEOUT_MS", 10_000, 1000, 60_000
)
AIRPERF_SAMPLE_INTERVAL_MS = _env_int(
    "MCNETEASE_AIRPERF_SAMPLE_INTERVAL_MS", 1000, 250, 10_000
)
AIRPERF_GRAPHICS_ENABLED = _env_bool("MCNETEASE_AIRPERF_GRAPHICS_ENABLED", False)
NATIVE_PERFORMANCE_SAMPLE_INTERVAL_MS = _env_int(
    "MCNETEASE_NATIVE_SAMPLE_INTERVAL_MS", 1000, 250, 10_000
)
TASK_PROGRESS_THROTTLE_MS = _env_int(
    "MCNETEASE_TASK_PROGRESS_THROTTLE_MS", 50, 0, 1000
)
LEVEL_DAT_MAX_BYTES = _env_int(
    "MCNETEASE_LEVEL_DAT_MAX_BYTES",
    32 * 1024 * 1024,
    1024,
    512 * 1024 * 1024,
)
LEVEL_DAT_MAX_DEPTH = _env_int("MCNETEASE_LEVEL_DAT_MAX_DEPTH", 64, 8, 512)
LEVEL_DAT_MAX_COLLECTION_ITEMS = _env_int(
    "MCNETEASE_LEVEL_DAT_MAX_COLLECTION_ITEMS",
    100_000,
    1,
    1_000_000,
)
LEVEL_DAT_BACKUP_SUFFIX = "_old"
LEVEL_DB_BACKUP_SUFFIX = _env("MCNETEASE_LEVEL_DB_BACKUP_SUFFIX", "_old")
LEVEL_DB_MAX_MANIFEST_BYTES = _env_int(
    "MCNETEASE_LEVEL_DB_MAX_MANIFEST_BYTES",
    64 * 1024 * 1024,
    1024,
    512 * 1024 * 1024,
)
LEVEL_DB_MAX_LOG_BYTES = _env_int(
    "MCNETEASE_LEVEL_DB_MAX_LOG_BYTES",
    512 * 1024 * 1024,
    1024,
    2 * 1024 * 1024 * 1024,
)
LEVEL_DB_MAX_TABLE_BYTES = _env_int(
    "MCNETEASE_LEVEL_DB_MAX_TABLE_BYTES",
    512 * 1024 * 1024,
    1024,
    2 * 1024 * 1024 * 1024,
)
LEVEL_DB_MAX_BLOCK_BYTES = _env_int(
    "MCNETEASE_LEVEL_DB_MAX_BLOCK_BYTES",
    64 * 1024 * 1024,
    1024,
    512 * 1024 * 1024,
)
LEVEL_DB_MAX_SCRIPT_BYTES = _env_int(
    "MCNETEASE_LEVEL_DB_MAX_SCRIPT_BYTES",
    64 * 1024 * 1024,
    1024,
    512 * 1024 * 1024,
)
LEVEL_DB_MAX_MESSAGEPACK_ITEMS = _env_int(
    "MCNETEASE_LEVEL_DB_MAX_MESSAGEPACK_ITEMS",
    1_000_000,
    1_000,
    10_000_000,
)
LEVEL_DB_MAX_TABLES = _env_int(
    "MCNETEASE_LEVEL_DB_MAX_TABLES",
    10_000,
    1,
    100_000,
)
LEVEL_DB_MAX_VIEW_ROWS = _env_int(
    "MCNETEASE_LEVEL_DB_MAX_VIEW_ROWS",
    100_000,
    100,
    1_000_000,
)
LEVEL_DB_VALUE_PREVIEW_CHARS = _env_int(
    "MCNETEASE_LEVEL_DB_VALUE_PREVIEW_CHARS",
    8 * 1024,
    512,
    1024 * 1024,
)

__all__ = [
    "APP_TITLE",
    "SPLASH_SUBTITLE",
    "APP_VERSION",
    "UPDATE_REPO",
    "UPDATE_ASSET_KEYWORD",
    "PROJECT_HOMEPAGE",
    "PRISMQML_HOMEPAGE",
    "INSTALLER_SILENT_ARGS",
    "ZIP_COMPRESSION_LEVEL",
    "AUDIT_MAX_FILE_NAME_CHARS",
    "AUDIT_MAX_TEXTURE_DIMENSION",
    "AUDIT_MAX_NETWORK_VERSION",
    "MCP_HOST",
    "MCP_PORT",
    "MCP_PATH",
    "MCP_PORT_MIN",
    "MCP_PORT_MAX",
    "MCP_STOP_TIMEOUT_MS",
    "TRACY_HOST",
    "TRACY_PORT",
    "TRACY_CAPTURE_SECONDS",
    "TRACY_CAPTURE_COOLDOWN_MS",
    "TRACY_PROBE_INTERVAL_MS",
    "PERFORMANCE_AUTO_STABILITY_MS",
    "AIRPERF_RUNTIME_DIR",
    "AIRPERF_HOST",
    "AIRPERF_X64_PORT",
    "AIRPERF_X86_PORT",
    "AIRPERF_RPC_TIMEOUT_MS",
    "AIRPERF_START_TIMEOUT_MS",
    "AIRPERF_SAMPLE_INTERVAL_MS",
    "AIRPERF_GRAPHICS_ENABLED",
    "NATIVE_PERFORMANCE_SAMPLE_INTERVAL_MS",
    "TASK_PROGRESS_THROTTLE_MS",
    "LEVEL_DAT_MAX_BYTES",
    "LEVEL_DAT_MAX_DEPTH",
    "LEVEL_DAT_MAX_COLLECTION_ITEMS",
    "LEVEL_DAT_BACKUP_SUFFIX",
    "LEVEL_DB_BACKUP_SUFFIX",
    "LEVEL_DB_MAX_MANIFEST_BYTES",
    "LEVEL_DB_MAX_LOG_BYTES",
    "LEVEL_DB_MAX_TABLE_BYTES",
    "LEVEL_DB_MAX_BLOCK_BYTES",
    "LEVEL_DB_MAX_SCRIPT_BYTES",
    "LEVEL_DB_MAX_MESSAGEPACK_ITEMS",
    "LEVEL_DB_MAX_TABLES",
    "LEVEL_DB_MAX_VIEW_ROWS",
    "LEVEL_DB_VALUE_PREVIEW_CHARS",
]
